version:  "3.9"

services:
  vault-service:
    image: "vault:latest"
    container_name: vault-service
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "00000000-0000-0000-0000-000000000000"
    ports:
      - "8200:8200"
    networks:
      - mired
networks:
  mired:
    external: true